### ISSUE TITLE
`winnow` package throwing error

### ISSUE THREAD

**Issue by metaproph3t** [ameliatastic/seahorse-lang#100]
I ran the following commands:

```bash
$ seahorse init <name>
$ cd <name>
$ seahorse build
```

It threw the following error:
```
Error: anchor build -p poseidon failed:

This is most likely a bug in the Seahorse compiler!

If you want to help the project, you can report this:
  - on the Seahorse Discord (http://discord.gg/4sFzH5pus8)
  - or as a Github issue (https://github.com/ameliatastic/seahorse-lang/issues).

Thanks!

error: package `winnow v0.4.4` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.62.0-dev
```

When I run
``` bash
$ rustc --version
```
I get `rustc 1.69.0`. 

As requested, I am reporting the error by creating an issue.

**Comment by acheroncrypto** [comment]
This error is not resulting from Seahorse. See https://github.com/solana-labs/solana/issues/31428 to understand why it's complaining about rustc version.

To fix this, add the latest git version of `anchor-spl` to your `Cargo.toml`

```toml
anchor-spl = { git = "https://github.com/coral-xyz/anchor" }
```

You can also choose to remove `anchor-spl` dependency if you are not using it. Seahorse comes with it by default afaik.

See full explanation: https://solana.stackexchange.com/a/6535/471

**Comment by metaproph3t** [comment]
The fix that you specified on stack exchange worked, sir. Closing.
