### ISSUE TITLE
Calculator test failing

### ISSUE THREAD

**Issue by josezy** [ameliatastic/seahorse-lang#21]
I was following the [official docs](https://seahorse-lang.org/docs/your-first-seahorse-program) to checkout the calculator example and noted the use of `Calculator` as seed in the program but also the use of `calculator-account` in the test, this throws an error:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1992441/195375549-a221f4ae-f37f-476e-9e5a-693663d76479.png">

I looked into the issue and changed `calculator-account` to `Calculator` in the test and it worked

<img width="733" alt="image" src="https://user-images.githubusercontent.com/1992441/195376069-c4d4b965-df02-4e60-a067-71d467d342ba.png">

**Comment by ameliatastic** [comment]
welp that's embarassing, i think i reran the tests with that correction and forgot to update it in the docs. thanks for notifying, will fix it now!
