### ISSUE TITLE
Nested mutable types in accounts

### ISSUE THREAD

**Issue by ameliatastic** [ameliatastic/seahorse-lang#33]
If you define an account type that has a mutable type as a field (like another class), it might not work. Since all mutable types get converted to a custom `Mutable<T>` type (which is just a wrapper around `Rc<RefCell<T>>` that allows some impls), an account can't store the `Mutable<T>`.

This is specialized for arrays, though - a class should be able to store an array type, and it will get converted to a `Mutable<[...]>` when the account gets loaded, then the raw data will be extracted and stored in the account when it gets stored back on the chain (at the end of the instruction).

A similar process could be performed for any other mutable type, but orchestrating everything is tricky because of nesting. If an account has a field, which is a class that has a field, which is a mutable type, then the account will need to store:

```rs
struct Account { field: Class }
struct Class { field: Type }
```

...but at runtime, we need to have something like:

```rs
struct LoadedAccount { field: Mutable<LoadedClass> }
struct LoadedClass { field: Mutable<Type> }
```

Right now, this is accomplished pretty well for accounts without nested mutable fields, but in the future this needs to work for anything imaginable.

**Comment by harsh4786** [comment]
does this derive AnchorSerialize and AnchorDeserialize on the structs that are to be nested?

**Comment by mcintyre94** [comment]
It doesn't currently, but I've been able to compile this:

```rs
// generate/mod.rs
            impl<T: AnchorSerialize> AnchorSerialize for Mutable<T> {
                fn serialize<W: std::io::Write>(
                    &self,
                    writer: &mut W,
                ) -> core::result::Result<(), std::io::Error> {
                    T::serialize(&self.0.borrow(), writer)
                }
            }

            impl<T: AnchorDeserialize> AnchorDeserialize for Mutable<T> {
                fn deserialize(buf: &mut &[u8]) -> core::result::Result<Self, std::io::Error> {
                    T::deserialize(buf).map(|obj| Mutable::new(obj))
                }
            }
```
