### ISSUE TITLE
Need support for passing Pubkeys and Arrays as seeds

### ISSUE THREAD

**Issue by harsh4786** [ameliatastic/seahorse-lang#35]
Currently, passing pubkeys and/or byte arrays as seeds is not supported by Seahorse compiler as it throws an error like seen in the screenshot, the same happens with an array of u8s or any other integer type
![Screenshot from 2022-10-27 21-31-34](https://user-images.githubusercontent.com/50767810/198343122-a81ab1a5-adc5-4950-887f-d23e7becfda8.png)

**Comment by mcintyre94** [comment]
- I think pubkey should be quite easy, we support `Signer` by storing its `.key()`, ie the public key
- Array of u8 is a minor regression, was quite simple to add previously: https://github.com/ameliatastic/seahorse-lang/pull/6/files
- For others integers we'd want to do something like `seeds = [data.to_le_bytes().as_ref()]`. I think we could do big or little endian, just need to be consistent so people know what to do on the client side.

**Comment by ameliatastic** [comment]
Yeah, integers are currently converted to little endian (`.to_le_bytes()`). Thanks for bringing this up @harsh4786! Always feel like there's more things that worked in v1 that were broken in v2 due to oversight.

**Comment by mcintyre94** [comment]
@harsh4786 Can you share an example file using integer types and u8s where you're seeing an error?
I can't repro them, eg this works: https://beta.solpg.io/635c3a7177ea7f12846aef05

**Comment by harsh4786** [comment]
I wanted to pass a fixed size array like a [u8, 32] ( [u8 ; 32] in rust) that wasn't working for me

**Comment by mcintyre94** [comment]
Hmm got it, I can repro that one: https://beta.solpg.io/635d6c6977ea7f12846aef07

```
Building...
Error: could not cast Array[u8, 2] as <Seed>.
17 |   fizzbuzz.init(payer = owner, seeds = [num, [x, y], xs])
```

I think that should be possible to support!

**Comment by mcintyre94** [comment]
Unfortunately it looks like the `Array[u8, n]` issue is another instance of #33 

Basically you end up with something like this in Anchor: `# [instruction (xs : Mutable < [u8 ; 2] >)]` and that doesn't work.
