### ISSUE TITLE
Support for passing structs as types in the account struct

### ISSUE THREAD

**Issue by harsh4786** [ameliatastic/seahorse-lang#37]
![Screenshot from 2022-10-28 01-26-40](https://user-images.githubusercontent.com/50767810/198386331-e9e89feb-d2f0-4c0b-9f87-190ac710b68c.png)
![Screenshot from 2022-10-28 01-26-48](https://user-images.githubusercontent.com/50767810/198386337-86024e75-3866-467c-88f7-6e3e307553c1.png)

currently we can't pass structs as types in Classes as the seahorse compiler doesn't derive AnchorSerialize and AnchorDeserialize traits on the struct like given in the screenshots

**Comment by ameliatastic** [comment]
Covered by #33
