### ISSUE TITLE
Unable to use lists/arrays in events

### ISSUE THREAD

**Issue by mcintyre94** [ameliatastic/seahorse-lang#64]
In addition to #61 (we'll need to add .clone for these types), there are some extra problems when using lists/arrays

- We don't have `AnchorSerialize` / `AnchorDeserialize` implemented for `Mutable[T]`. See https://github.com/ameliatastic/seahorse-lang/issues/33#issuecomment-1328260179 for a potential implementation
- The IDL generates the `Mutable` type 
```
        {
          "name": "items",
          "type": {
            "defined": "Mutable<Vec<u8>>"
          },
          "index": false
        },
```

**Comment by ameliatastic** [comment]
Yeah that's a big problem. What Seahorse type does that IDL come from?

**Comment by anoushk1234** [comment]
> Yeah that's a big problem. ~What Seahorse type does that IDL come from?~ update: duh it's a List[u8], for some reason I thought Anchor was coercing arrays to Vec

since this is working now we can close this issue
