### ISSUE TITLE
TokenAccount doesn't have mint

### ISSUE THREAD

**Issue by anoushk1234** [ameliatastic/seahorse-lang#87]
##### Problem
- TokenAccounts can have constraints in anchor accounts which check the mint, authority and freeze authority but currently there's not way to check the mint of a TokenAccount.

##### Solution
- Add a mint method to TokenAccount that gives the mint of the account.

**Comment by ameliatastic** [comment]
`TokenAccount` does have a `.mint()` method. This was added pretty recently, you might be on an old version of Seahorse.

**Comment by anoushk1234** [comment]
> `TokenAccount` does have a `.mint()` method. This was added pretty recently, you might be on an old version of Seahorse.

Yes after updating to 0.2.6 it is available, thanks!
